// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Extensions.ServiceCollectionExtensions.AddGoogleServices(Microsoft.Extensions.DependencyInjection.IServiceCollection,Google.Apis.Services.BaseClientService.Initializer)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MaximEmmBots.Models.HealthChecks.HealthCheckEntry.Uris")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "<Pending>", Scope = "member", Target = "~P:MaximEmmBots.Models.HealthChecks.HealthCheckUriItem.Tests")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.BotHandler.HandleError(System.Exception,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.BotHandler.HandleUpdate(Telegram.Bot.Types.Update,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.BotHandlerService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Context.#ctor(Microsoft.Extensions.Options.IOptions{MaximEmmBots.Options.DataOptions},Microsoft.Extensions.Logging.ILogger{MaximEmmBots.Services.Context})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.CultureService.CultureFor(MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.Globalization.CultureInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.CultureService.ModelFor(MaximEmmBots.Models.Json.Restaurants.Restaurant)~MaximEmmBots.Models.Json.LocalizationModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.CultureService.NowFor(MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.CultureService.TimeZoneFor(MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.TimeZoneInfo")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.DistributionBot.DistributionBotSheetsService.ExecuteAsync(MaximEmmBots.Models.Json.Restaurants.Restaurant,System.Threading.CancellationToken,System.Nullable{System.DateTime},System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.GuestsBot.GuestsBotSheetsService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.GuestsBot.WorkerService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.ReviewBot.WorkerService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.ReviewBot.WorkerService.GetNotifierTask(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.ReviewBot.WorkerService.GetWorkerTask(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Scheduling.SchedulingService.GetMonthlyDelay(MaximEmmBots.Services.Scheduling.IScheduler,MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.TimeSpan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Scheduling.SchedulingService.GetWeeklyDelay(MaximEmmBots.Services.Scheduling.IScheduler,MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.TimeSpan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Scheduling.SchedulingService.RunSchedulerAsync(MaximEmmBots.Services.Scheduling.IScheduler,MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.StatsBot.WorkerService.RunChartHandlerAsync(MaximEmmBots.Models.Json.Restaurants.Restaurant,MaximEmmBots.Models.Json.Restaurants.StatsBot.StatsBotScheduler,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Scheduling.SchedulingService.RunSchedulerAsync(MaximEmmBots.Services.Scheduling.IScheduler,MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.Scheduling.SchedulingService.RunSchedulerAsync(MaximEmmBots.Services.Scheduling.IScheduler,MaximEmmBots.Models.Json.Restaurants.Restaurant)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.StatsBot.ChartClient.LoadDoughnutPieChartAsync(System.IO.Stream,System.Collections.Generic.ICollection{MaximEmmBots.Models.Charts.PieChartItem})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.StatsBot.ChartClient.LoadDoughnutPieChartAsync(System.IO.Stream,System.Collections.Generic.ICollection{MaximEmmBots.Models.Charts.PieChartItem})~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.MailBot.WorkerService.YieldChecklistWatchdogEntryAsync(System.Collections.Generic.IList{System.Collections.Generic.IList{System.Object}},System.Threading.CancellationToken)~System.Collections.Generic.IAsyncEnumerable{MaximEmmBots.Models.Mongo.SentChecklist}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.BotHandler.HandleUpdate(Telegram.Bot.Types.Update,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.DistributionBot.DistributionBotSheetsService.ExecuteAsync(MaximEmmBots.Models.Json.Restaurants.Restaurant,System.Threading.CancellationToken,System.Nullable{System.DateTime},System.Int32)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.GoogleSheetsService.GetValueRangeAsync(System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Google.Apis.Sheets.v4.Data.ValueRange}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.GuestsBot.GuestsBotSheetsService.ExecuteAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.MailBot.WorkerService.RunChecklistWatchdogForEntryAsync(MaximEmmBots.Services.MailBot.WorkerService.ChecklistWatchdogEntry,System.Collections.Concurrent.BlockingCollection{MaximEmmBots.Models.Mongo.SentChecklist},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "<Pending>", Scope = "member", Target = "~M:MaximEmmBots.Services.DistributionBot.DistributionBotSheetsService.ExecuteManyAsync(System.Collections.Generic.ICollection{MaximEmmBots.Models.Json.Restaurants.Restaurant},System.Threading.CancellationToken,System.Int32,System.Nullable{System.DateTime})~System.Threading.Tasks.Task")]